name: CI
on: push

jobs:
  test-lint-typecheck:
    name: Run Ruff, Pytest, and Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync

      - uses: astral-sh/ruff-action@v3

      - name: Run Pytest (Unit Tests)
        run: uv run pytest --tb=short --disable-warnings -v --maxfail=1 --junitxml=test-results.xml

      - if: always()
        uses: pmeier/pytest-results-action@v0.6.0
        with:
          path: test-results.xml
          summary: true
          display-options: fEXIT
          title: "Test Results Toby's"

      - name: Run Pyright (Type Checking)
        run: uvx ty check .
