name: CI
on: push

jobs:
  test-lint-typecheck:
    name: Run Ruff, Pytest, and Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync

      - name: Run Ruff (Linting)
        run: uvx ruff check --output-format=github .

      - name: Run Pytest (Unit Tests)
        run: uv run pytest --tb=short --disable-warnings

      - name: Run Pyright (Type Checking)
        run: uvx ty check .
